export const tagList = {
  CentOS: { id: 1, name: 'CentOS' },
  Tesseract: { id: 2, name: 'Tesseract' },
  Chromium: { id: 3, name: 'Chromium' },
  NodeJS: { id: 4, name: 'Node.js' },
  Puppeteer: { id: 5, name: 'Puppeteer' },
  GoogleChrome: { id: 6, name: 'Google Chrome' },
  Selenium: { id: 7, name: 'Selenium' },
  Lighthouse: { id: 8, name: 'Lighthouse' },
  AlpineLinux: { id: 9, name: 'Alpine Linux' },
  NLTK: { id: 10, name: 'NLTK' },
  Python: { id: 11, name: 'Python' },
  Homestead: { id: 12, name: 'Homestead' },
  HeidiSQL: { id: 13, name: 'HeidiSQL' },
  PostgreSQL: { id: 14, name: 'PostgreSQL' },
  PHP: { id: 15, name: 'PHP' },
  VSCode: { id: 16, name: 'VSCode' },
  Xdebug: { id: 17, name: 'Xdebug' },
  MarkedJS: { id: 18, name: 'Marked.js' },
  NuxtJS: { id: 19, name: 'Nuxt.js' },
  JavaScript: { id: 20, name: 'JavaScript' },
  HTML: { id: 21, name: 'HTML' }
}
